# Setup
title:   Wire Brand
tagline: Brand assets & styleguide
baseurl: ""

highlighter: rouge
markdown: kramdown

# sass:
#     style: compressed
#     sass_dir: stylesheets

# exclude: ["gulpfile.js", "package.js", "node_modules"]
exclude: ["ReadMe.md"]

# version: "0.0.1"
