# Setup
title: Brand Elements
url: https://wearezeta.github.io/brand/
baseurl: "/brand"

highlighter: rouge
markdown: kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# exclude: ["gulpfile.js", "package.js", "node_modules"]
exclude: ["ReadMe.md"]

# Custom vars
version: "0.0.2"
github:
  repo:  https://github.com/wearezeta/brand
